version: '3.4'
services:
  notebook_worker:
    image: notebook_worker
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes: # mount a directory for the sqlite database
      - ./data:/data
  ### MySQL database
  #db:
  #  image: mysql:latest
  #  ports:
  #    - 3306:3306
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: notebook
  #    MYSQL_USER: notebook
  #    MYSQL_PASSWORD: notebook
  #  volumes:
  #    - my-datavolume:/var/lib/mysql
#volumes:
#  my-datavolume: