on: [pull_request]
name: 1password Testing
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure 1Password Connect
        uses: 1password/load-secrets-action/configure@v1
        with:
          # Persist the 1Password Service Account token. This will grant
          # all steps of the job access to the token.
          service-account-token: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Load Docker credentials
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          TEST_USERNAME: op://${{ env.VAULT_ID }}/test/username

      - name: Print masked secret
        run: echo "Secret= ${{ env.TEST_USERNAME }}"
        
    
