on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "fake" ]
name: 1password2 Testing
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          SECRET: op://github-actions/test/username

      - name: Print masked secret
        run: echo "Secret; $SECRET"
        # Prints: Secret; ***