on: push
name: 1password Testing
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
          service-account-token: ${{ secrets.OP_CONNECT_TOKEN }}
        env:
          OP_CONNECT_HOST: ${{ env.ONEP_URL }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          # OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          SECRET: op://${{ env.VAULT_ID }}/test/username

      - name: Print masked secret
        run: echo "Secret= ${{ env.SECRET }}"
        # Prints: Secret: ***
