name: "Build and push to ECR"
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  BuildAndPushImageToECR:
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          AWS_ACCESS_KEY_ID: op://github-actions/aws/id
          AWS_SECRET_ACCESS_KEY: op://github-actions/aws/token

      - name: Print masked secret
        run: echo "Secret; $SECRET. AWS_ACCESS_KEY_ID; $AWS_ACCESS_KEY_ID. AWS_SECRET_ACCESS_KEY; $AWS_SECRET_ACCESS_KEY"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}  #${{ secrets.AWS_ACCESS_KEY_ID }} 
          #$AWS_ACCESS_KEY_ID
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}   #${{ secrets.AWS_SECRET_ACCESS_KEY}}    
          #$AWS_SECRET_ACCESS_KEY
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "tenx-notebook-server"
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
